import { NewsEvent } from './types';

export const easyEvents: NewsEvent[] = [
  {
    id: 'nfp_1',
    name: 'Non-Farm Payroll (NFP)',
    time: '19:30',
    explanation: 'Laporan NFP mengukur perubahan jumlah orang yang dipekerjakan selama bulan lalu (tanpa industri pertanian). Secara historis, pasar saat ini sedang memperhatikan resiko resesi, dan data tenaga kerja sangat krusial.',
    previous: '250K',
    forecast: '200K',
    actualUp: '275K',
    actualDown: '150K',
    explanationUp: 'Data NFP dirilis jauh di atas perkiraan! Kondisi tenaga kerja AS sangat solid, memicu penguatan USD yang signifikan dan menekan aset komoditas seperti Gold.',
    explanationDown: 'Data NFP meleset jauh dari ekspektasi. Muncul kepanikan melambatnya ekonomi AS yang memicu pelemahan USD secara drastis.',
  },
  {
    id: 'cpi_1',
    name: 'Consumer Price Index (CPI)',
    time: '19:30',
    explanation: 'CPI mengukur persentase perubahan harga barang dan jasa yang dikonsumsi masyarakat. Belakangan ini The Fed sedang memantau ketat inflasi untuk menentukan pemangkasan suku bunga.',
    previous: '3.1%',
    forecast: '3.0%',
    actualUp: '3.4%',
    actualDown: '2.8%',
    explanationUp: 'Kejutan inflasi! CPI melonjak tak terduga, pupus harapan pemangkasan suku bunga The Fed. USD menguat drastis.',
    explanationDown: 'Inflasi turun lebih cepat dari prediksi! Pasar optimis akan ada cut rate, USD mengalami pelemahan hebat.',
  },
  {
    id: 'gdp_1',
    name: 'Gross Domestic Product (GDP)',
    time: '19:30',
    explanation: 'Pertumbuhan ekonomi kuartalan AS. Data ini adalah indikator terluas untuk memperkirakan kesehatan ekonomi. Pelaku pasar masih meraba apakah soft-landing akan terjadi.',
    previous: '2.4%',
    forecast: '2.0%',
    actualUp: '2.8%',
    actualDown: '1.2%',
    explanationUp: 'Ekonomi AS luar biasa tangguh. Pertumbuhan GDP di atas batas normal menyingkirkan isu resesi, USD diburu investor.',
    explanationDown: 'Penurunan drastis pada GDP menimbulkan ketakutan hard-landing (resesi), USD ditinggalkan dan investor beralih ke safe-haven.',
  },
  {
    id: 'unemp_1',
    name: 'Unemployment Rate',
    time: '19:30',
    explanation: 'Tingkat pengangguran bulanan AS. Menunjukkan persentase total angkatan kerja yang tidak memiliki pekerjaan dan sedang mencari pekerjaan secara aktif.',
    previous: '3.8%',
    forecast: '3.9%',
    actualUp: '3.7%',
    actualDown: '4.1%',
    explanationUp: 'Tingkat pengangguran secara mengejutkan turun drastis! Sektor tenaga kerja AS kuat, mendorong USD memantul tajam.',
    explanationDown: 'Ledakan pengangguran terjadi. Sinyal bahaya ekonomi melemah yang membuat pasar yakin suku bunga akan dipangkas. USD melemah drastis.',
  },
  {
    id: 'claims_1',
    name: 'Initial Jobless Claims',
    time: '19:30',
    explanation: 'Jumlah individu yang mengajukan asuransi pengangguran untuk pertama kalinya selama seminggu terakhir. Berdampak besar dalam mengukur kesehatan mingguan tenaga kerja.',
    previous: '215K',
    forecast: '220K',
    actualUp: '190K',
    actualDown: '240K',
    explanationUp: 'Pengajuan tunjangan pengangguran jauh di bawah prediksi, menandakan perusahaan mempertahankan pekerja. USD melonjak tajam.',
    explanationDown: 'Tingkat PHK mingguan memburuk dan jauh melampaui prediksi! Kondisi ketenagakerjaan melemah menekan sentimen USD.',
  },
  {
    id: 'trade_1',
    name: 'Trade Balance',
    time: '19:30',
    explanation: 'Perbedaan antara nilai impor dan ekspor barang serta jasa dalam satu bulan. Defisit yang mengecil menunjukkan kekuatan ekspor AS.',
    previous: '-$62.5B',
    forecast: '-$63.0B',
    actualUp: '-$55.0B',
    actualDown: '-$70.0B',
    explanationUp: 'AS mencetak penurunan defisit perdagangan tajam berkat ledakan ekspor manufaktur. Permintaan global pulih, USD didukung penuh.',
    explanationDown: 'Defisit dagang menganga lebih lebar dari prediksi! Ekspor AS anjlok, menimbulkan kekhawatiran aliran dolar, USD terperosok.',
  },
  {
    id: 'ism_mfg_1',
    name: 'ISM Manufacturing PMI',
    time: '21:00',
    explanation: 'Indeks manajer pembelian sektor manufaktur yang mengukur tingkat aktivitas industri AS. Angka di atas 50 berarti ekspansi, di bawah 50 kontraksi.',
    previous: '49.1',
    forecast: '50.0',
    actualUp: '52.5',
    actualDown: '46.0',
    explanationUp: 'Pabrikan AS ekspansi tajam! Terobosan besar dalam pesanan baru membuat optimisme bisnis meroket. USD melesat tajam dan kuat.',
    explanationDown: 'Kinerja manufaktur anjlok jauh ke jurang kontraksi. Ketakutan stagflasi membayangi, menekan indeks USD di sesi perdagangan.',
  },
  {
    id: 'ism_srv_1',
    name: 'ISM Non-Manufacturing PMI',
    time: '21:00',
    explanation: 'Mengukur aktivitas bisnis sektor jasa AS (sekitar 70% dari GDP AS). Sangat penting untuk melihat kekuatan daya tahan ekonomi AS.',
    previous: '51.5',
    forecast: '52.0',
    actualUp: '54.5',
    actualDown: '49.0',
    explanationUp: 'Sektor jasa AS terbang tinggi mencetak pertumbuhan ekstra cepat. Menggeser sinyal pelonggaran the Fed. USD menyedot likuiditas pasar.',
    explanationDown: 'Mesin ekonomi utama AS terhenti! Sektor jasa menembus batas kontraksi. Alarm resesi diaktifkan, safe-haven dibeli, USD melemah.',
  },
  {
    id: 'bld_prm_1',
    name: 'Building Permits',
    time: '19:30',
    explanation: 'Laporan indikator jumlah izin yang diberikan untuk proyek konstruksi swasta baru. Indikator utama kebangkitan ekonomi dasar.',
    previous: '1.45M',
    forecast: '1.48M',
    actualUp: '1.60M',
    actualDown: '1.35M',
    explanationUp: 'Sektor properti bangkit pesat dengan angka izin membangun jauh melesat. Uang baru mengalir ke pasar perumahan, mendukung USD.',
    explanationDown: 'Pembangunan properti lumpuh terjerat suku bunga KPR tinggi. Pasar rumah macet, USD kehilangan momentum pertumbuhan.',
  },
  {
    id: 'c_conf_1',
    name: 'CB Consumer Confidence',
    time: '21:00',
    explanation: 'Tingkat optimisme konsumen terhadap aktivitas ekonomi. Konsumen yang lebih optimis memicu pertumbuhan kuat lewat belanja mereka.',
    previous: '106.0',
    forecast: '107.5',
    actualUp: '112.0',
    actualDown: '100.0',
    explanationUp: 'Konsumen AS kembali boros dan sangat optimis pada perekonomian! Harapan stabilitas menarik minat The Fed tetap ketat. USD roket.',
    explanationDown: 'Kepanikan terlihat dari sentimen pesimis yang jebol luar biasa. Warga menahan konsumsi akibat pengetatan kredit, USD pun tersandung drastis.',
  },
  {
    id: 'ex_hm_1',
    name: 'Existing Home Sales',
    time: '21:00',
    explanation: 'Mengukur penjualan properti dari sisi bangunan yang sudah pernah dihuni. Berkorelasi kuat dengan sirkulasi ekonomi berantai perumahan.',
    previous: '4.00M',
    forecast: '3.90M',
    actualUp: '4.30M',
    actualDown: '3.60M',
    explanationUp: 'Pasar properti kebal meski suku bunga gila. Penjualan meleset ke sisi atas mencerminkan soliditas ekonomi nyata AS. USD hijau.',
    explanationDown: 'Penjualan rumah bekas ambruk parah mencapai titik terendah sedekade. Efek suku bunga terasa menyakitkan, the FED goyah, USD anjlok.',
  },
  {
    id: 'phl_fed_1',
    name: 'Philly Fed Manufacturing Index',
    time: '19:30',
    explanation: 'Survei kondisi bisnis dari produsen di sekitar Philadelphia. Sering dianggap sebagai indikator leading untuk indeks ISM secara nasional.',
    previous: '2.5',
    forecast: '3.0',
    actualUp: '10.5',
    actualDown: '-5.0',
    explanationUp: 'Pabrikan timur AS ekspansi gila-gilaan, merusak skenario soft-landing the FED. Industri sangat panas, USD lompat!',
    explanationDown: 'Data negatif Philadelphia mengecewakan. Industri terpukul resesi lokal yang dapat menular. Mata uang bereaksi dengan dumping tajam atas USD.',
  },
  {
    id: 'con_us_1',
    name: 'UoM Consumer Sentiment',
    time: '21:00',
    explanation: 'Hasil survei sentimen ekonomi Universitas Michigan. Salah satu barometer konsumen terkuat bersama CB Consumer Confidence.',
    previous: '78.0',
    forecast: '78.5',
    actualUp: '82.0',
    actualDown: '72.0',
    explanationUp: 'Sentimen warga Michigan memimpin lompatan konsumerisme nasional! USD kembali gagah didukung harapan fundamental mikro AS.',
    explanationDown: 'Rakyat kehilangan asa, index terjun jauh karena daya tarik inflasi belum reda. Kecemasan makro memaksa modal keluar dari USD.',
  }
];

export const normalEvents: NewsEvent[] = [
  {
    id: 'ppi_1',
    name: 'Core PPI m/m',
    time: '19:30',
    explanation: 'Indeks Harga Produsen Inti (PPI) bulanan menunjukkan perubahan harga jual oleh produsen. Belakangan ini biaya pabrikan meningkat akibat rantai pasok.',
    previous: '0.2%',
    forecast: '0.1%',
    actualUp: '0.4%',
    actualDown: '-0.1%',
    explanationUp: 'Biaya produsen meroket tajam, mengindikasikan inflasi tertunda akan segera sampai ke konsumen. USD melesat tajam.',
    explanationDown: 'Biaya pabrikan anjlok drastis (deflasi produsen). Suku bunga tampaknya memukul keras industri, USD melemah gila-gilaan.',
  },
  {
    id: 'retail_1',
    name: 'Retail Sales m/m',
    time: '19:30',
    explanation: 'Penjualan Ritel mengukur nilai total penjualan di tingkat ritel. Konsumtifnya warga AS adalah motor penggerak ekonomi, akankah masih bertahan?',
    previous: '0.4%',
    forecast: '-0.2%',
    actualUp: '1.1%',
    actualDown: '-0.8%',
    explanationUp: 'Belanja dan konsumsi warga AS ternyata masih liar! Data Retail Sales positif meyakinkan sentimen risk-on untuk USD.',
    explanationDown: 'Masyarakat AS menahan uang mereka. Daya beli anjlok dalam, resesi ritel tampak di depan mata. Tembok USD runtuh.',
  },
  {
    id: 'fomc_1',
    name: 'FOMC Statement & Fed Rate',
    time: '02:00',
    explanation: 'Bank Sentral AS (The Fed) akan mengumumkan kebijakan moneter dan suku bunga terbarunya (Federal Funds Rate). Drama volatilitas pasar tertinggi ada disini.',
    previous: '5.25%',
    forecast: '5.25%',
    actualUp: '5.50%',
    actualDown: '5.00%',
    explanationUp: 'Kejutan Hawkish! The Fed secara tak terduga MENAIKKAN suku bunga (Hike). Sesuatu yang tak di tebak oleh pasar, kepanikan massal melambungkan USD.',
    explanationDown: 'Dovish! Suku bunga akhirnya di PANGKAS. Pesta pora di Wall Street dimulai, dan USD terjun bebas tanpa keraguan.',
  },
  {
    id: 'jolts_1',
    name: 'JOLTs Job Openings',
    time: '21:00',
    explanation: 'Melacak lowongan pekerjaan yang ada. Indikator paling favorit bagi ketua FED (Jerome Powell) dalam menilai overheating ketenagakerjaan.',
    previous: '8.80M',
    forecast: '8.70M',
    actualUp: '9.20M',
    actualDown: '8.10M',
    explanationUp: 'Lowongan kerja meledak lagi! Bos butuh tambahan orang mendadak. Kondisi ini membuat The Fed bisa menahan bunga tinggi lama. USD naik cepat.',
    explanationDown: 'Sektor tenaga kerja mengerut, lowongan dicabut banyak perusahaan. Angin segar the FED cut makin lebar, USD merosot curam.',
  },
  {
    id: 'adp_1',
    name: 'ADP Non-Farm Employment Change',
    time: '19:15',
    explanation: 'Estimasi awal swasta mengenai jumlah tenaga kerja baru di AS sebelum laporan utama NFP keluar hari Jumat.',
    previous: '160K',
    forecast: '150K',
    actualUp: '220K',
    actualDown: '110K',
    explanationUp: 'Data serapan tenaga kerja swasta (ADP) jauh melompati perkiraan. Ekonomi korporat terlihat solid, menopang reli kuat USD sesaat.',
    explanationDown: 'Kontraksi anjlok di penyerapan swasta, memicu alarm The Fed harus lekas bertindak menyelamatkan iklim perusahaan. USD jeblok parah.',
  },
  {
    id: 'core_pce_1',
    name: 'Core PCE Price Index m/m',
    time: '19:30',
    explanation: 'Indikator Inflasi "paling disukai" oleh FED. Memantau daya belik konsumen atas barang inti (Core Personal Consumption Expenditure).',
    previous: '0.2%',
    forecast: '0.2%',
    actualUp: '0.4%',
    actualDown: '0.0%',
    explanationUp: 'PCE Inti secara tak disangka terbakar panas. Resiko inflasi naik lagi menyita wacana penurunan suku. USD otomatis merobek atap!',
    explanationDown: 'Dis-inflasi sudah jelas. PCE mendingin sampai nol. Harapan pemangkasan suku bunga tereksekusi segera, uang AS diobral murmer oleh trader.',
  },
  {
    id: 'dur_ord_1',
    name: 'Core Durable Goods Orders',
    time: '19:30',
    explanation: 'Perubahan nilai order pabrikan AS terhadap barang tahan lama. Core = di luar sektor transportasi yang rentan berfluktuasi ekstrem bulanan.',
    previous: '0.3%',
    forecast: '0.1%',
    actualUp: '0.9%',
    actualDown: '-0.5%',
    explanationUp: 'Permintaan barang modal raksasa meledak tajam. Kepercayaan tingkat perusahan (capex) memimpin optimisme. USD langsung tegak keatas.',
    explanationDown: 'Investasi perusahaan AS lumpuh dan pesanan pesawat ditarik besar-besaran. Data ekonomi mendingin terlalu drastis. USD ambruk serentak.',
  },
  {
    id: 'fmi_1',
    name: 'Flash Manufacturing PMI',
    time: '20:45',
    explanation: 'Data sangat awal (flash) indikator tingkat produksi manufaktur nasional, diterbitkan oleh S&P Global.',
    previous: '49.9',
    forecast: '50.1',
    actualUp: '51.5',
    actualDown: '47.5',
    explanationUp: 'Flash Manufacturing menyembur keluar di area ekspansi tak terprediksi! Harapan resesi tertepis seutuhnya, gelagat pendorong positif bagi nilai dolar.',
    explanationDown: 'Kontraksi berlanjut dan memburuk! Industri tenggelam di zona mematikan memaksa the Fed merevisi dot-plots secepatnya. USD terperosok beruntun.',
  },
  {
    id: 'fsi_1',
    name: 'Flash Services PMI',
    time: '20:45',
    explanation: 'Data indikasi pesanan awal yang mencetak detak jantung pertama industri jasa nasional bulan berjalan.',
    previous: '52.0',
    forecast: '52.5',
    actualUp: '54.5',
    actualDown: '49.5',
    explanationUp: 'Services PMI melambung fantastik membawa Amerika jauh dari zona perlemahan global. USD perkasa mengalahkan komoditas.',
    explanationDown: 'Menyusul angka buruk industri lain, jasa anjlok di bawah zona krusial 50,0. USD dump!',
  },
  {
    id: 'foc_1',
    name: 'Factory Orders m/m',
    time: '21:00',
    explanation: 'Total dolar pada pesanan barang yang sedang dikerjakan seluruh industri Amerika.',
    previous: '1.2%',
    forecast: '1.0%',
    actualUp: '2.5%',
    actualDown: '-1.0%',
    explanationUp: 'Pesanan barang di pabrik lokal AS membengkak drastis tak logis. Pertumbuhan riil menekan kekhawatiran dan memicu dolar naik kelas!',
    explanationDown: 'Permintaan manufaktur drop pesat. Mesin cetak industri mulai sepi dari bahan baku. Mata uang USD terguling curam di papan valas.',
  },
  {
    id: 'emp_st_1',
    name: 'Empire State Mfg Index',
    time: '19:30',
    explanation: 'Indeks awal kekuatan manufaktur di area state kota padat bisnis nomor-1 AS, New York.',
    previous: '-10.5',
    forecast: '-5.0',
    actualUp: '3.0',
    actualDown: '-20.0',
    explanationUp: 'Pabrikan New York lepas dari jurang kontraksi masuk ke area hijau seketika. Awal menawan untuk the state of USA economy. USD Buy-off limit.',
    explanationDown: 'Mala petaka di New York! Keadaan manufaktur di daerah kunci AS terpuruk pada level pesimistis historikal. USD ditumbangkan sekilat.',
  },
  {
    id: 'pis_1',
    name: 'Personal Income m/m',
    time: '19:30',
    explanation: 'Presentase fluktuasi total pendapatan nasional Amerika dari gaji bulanan.',
    previous: '0.4%',
    forecast: '0.4%',
    actualUp: '0.8%',
    actualDown: '0.0%',
    explanationUp: 'Hore! Orang Amerika mendadak jauh lebih kaya ditopang peningkatan upah kotor! Potensi pengetatan the fed jadi rasional kembali, USD naik mantap!',
    explanationDown: 'Gaji stuck di tempat, warga kekurangan daya untuk terus membelanjakan modal bebas mereka. Tekanan USD merendah kembali.',
  }
];

export const getAllEventsForMode = (mode: string) => {
  if (mode === 'easy') return [...easyEvents];
  if (mode === 'normal') return [...normalEvents];
  // Hard mode has both but hides previous
  return [...easyEvents, ...normalEvents];
};

export const getRandomEvent = (mode: string, excludeIds: string[]) => {
  const events = getAllEventsForMode(mode).filter(e => !excludeIds.includes(e.id));
  if (events.length === 0) {
    // If we exhausted all, reset excluding (ideally shouldn't happen before 10 wins)
    return getAllEventsForMode(mode)[Math.floor(Math.random() * getAllEventsForMode(mode).length)];
  }
  return events[Math.floor(Math.random() * events.length)];
};
